// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBT23e5PP4OdYKjNKrK_chW4Fqfucmabdw',
    appId: '1:572226647997:web:46c880b29baca0894e04d4',
    messagingSenderId: '572226647997',
    projectId: 'ecommerce-9cd8e',
    authDomain: 'ecommerce-9cd8e.firebaseapp.com',
    storageBucket: 'ecommerce-9cd8e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiGiq69z3RzuERLLNTLpKq5_9dKwApi-E',
    appId: '1:572226647997:android:1b970168520b99b94e04d4',
    messagingSenderId: '572226647997',
    projectId: 'ecommerce-9cd8e',
    storageBucket: 'ecommerce-9cd8e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVllht8GzA4bWyRQnJ5BgQYclLhtBLFK8',
    appId: '1:572226647997:ios:0ec2c2eeb57782164e04d4',
    messagingSenderId: '572226647997',
    projectId: 'ecommerce-9cd8e',
    storageBucket: 'ecommerce-9cd8e.appspot.com',
    iosBundleId: 'com.example.fashion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVllht8GzA4bWyRQnJ5BgQYclLhtBLFK8',
    appId: '1:572226647997:ios:0ec2c2eeb57782164e04d4',
    messagingSenderId: '572226647997',
    projectId: 'ecommerce-9cd8e',
    storageBucket: 'ecommerce-9cd8e.appspot.com',
    iosBundleId: 'com.example.fashion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBT23e5PP4OdYKjNKrK_chW4Fqfucmabdw',
    appId: '1:572226647997:web:6009bf3027db25764e04d4',
    messagingSenderId: '572226647997',
    projectId: 'ecommerce-9cd8e',
    authDomain: 'ecommerce-9cd8e.firebaseapp.com',
    storageBucket: 'ecommerce-9cd8e.appspot.com',
  );
}
